/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painlessgui3;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import painlessgui.print;
import painlessgui.resultAtasDua;
import painlessgui.start;

/**
 *
 * @author BiBul
 */
public class gendut extends javax.swing.JFrame {

    /**
     * Creates new form gendut
     */
    public gendut() {
        initComponents();
        setTitle("PainLESS v1.0.0");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        detail = new javax.swing.JButton();
        satuan = new javax.swing.JLabel();
        endo = new javax.swing.JToggleButton();
        DONE = new javax.swing.JButton();
        namaUser2 = new javax.swing.JLabel();
        tinggiBadan2 = new javax.swing.JLabel();
        beratBadan2 = new javax.swing.JLabel();
        jenisKelamin2 = new javax.swing.JLabel();
        umurUser2 = new javax.swing.JLabel();
        bmrResult2 = new javax.swing.JLabel();
        gizi2 = new javax.swing.JLabel();
        karbo2 = new javax.swing.JLabel();
        proto2 = new javax.swing.JLabel();
        lemaks2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        resultt3 = new javax.swing.JLabel();
        fatBody = new javax.swing.JLabel();
        hearts = new javax.swing.JLabel();
        fatbod = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detail.setText("Detail");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        jPanel1.add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 583, 100, 40));

        satuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/cm  kg    thn  Kkl  Kkl  gram_day  gram_day  gram_day.png"))); // NOI18N
        jPanel1.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 80, -1));

        endo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/ENDOMORPH.png"))); // NOI18N
        endo.setContentAreaFilled(false);
        endo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endoActionPerformed(evt);
            }
        });
        jPanel1.add(endo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        DONE.setText("DONE");
        DONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DONEActionPerformed(evt);
            }
        });
        jPanel1.add(DONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 583, 100, 40));

        namaUser2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        namaUser2.setText("jLabel1");
        jPanel1.add(namaUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        tinggiBadan2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tinggiBadan2.setText("jLabel1");
        jPanel1.add(tinggiBadan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 30, -1));

        beratBadan2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beratBadan2.setText("jLabel1");
        jPanel1.add(beratBadan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 30, -1));

        jenisKelamin2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenisKelamin2.setText("jLabel1");
        jPanel1.add(jenisKelamin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 90, -1));

        umurUser2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        umurUser2.setText("jLabel1");
        jPanel1.add(umurUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 40, -1));

        bmrResult2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bmrResult2.setText("jLabel1");
        jPanel1.add(bmrResult2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 50, -1));

        gizi2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gizi2.setText("jLabel1");
        jPanel1.add(gizi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 50, -1));

        karbo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        karbo2.setText("jLabel1");
        jPanel1.add(karbo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 50, -1));

        proto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        proto2.setText("jLabel1");
        jPanel1.add(proto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 50, -1));

        lemaks2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lemaks2.setText("jLabel1");
        jPanel1.add(lemaks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 50, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/PainLESS.png"))); // NOI18N
        logo.setText("jLabel1");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 330, -1));

        resultt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/ Tinggi Badan  Berat Badan   Jenis Kelamin  Umur   BMR  Kebutuh.png"))); // NOI18N
        resultt3.setText("jLabel1");
        jPanel1.add(resultt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 180, -1));

        fatBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/fat body.png"))); // NOI18N
        fatBody.setText("jLabel2");
        jPanel1.add(fatBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 480, -1));

        hearts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/heart-cardiogram-health-icon-image-vector-12781394.png"))); // NOI18N
        hearts.setText("jLabel2");
        jPanel1.add(hearts, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 410, -1));

        fatbod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/FAT.png"))); // NOI18N
        fatbod.setText("jLabel2");
        jPanel1.add(fatbod, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 380, 610));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui3/Cloud.png"))); // NOI18N
        bg.setText("jLabel6");
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DONEActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            start e = new start();
            e.setVisible(true);
    }//GEN-LAST:event_DONEActionPerformed

    private void endoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endoActionPerformed
if ( endo.isSelected()){
    fatbod.setIcon( new ImageIcon(getClass().getResource("/painlessgui3/endo.png")));
}
else {
     fatbod.setIcon( new ImageIcon(getClass().getResource("/painlessgui3/FAT.png")));
}
    }//GEN-LAST:event_endoActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed

            print e = new print();
            e.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_detailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gendut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gendut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gendut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gendut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gendut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DONE;
    public static javax.swing.JLabel beratBadan2;
    private javax.swing.JLabel bg;
    public static javax.swing.JLabel bmrResult2;
    private javax.swing.JButton detail;
    private javax.swing.JToggleButton endo;
    private javax.swing.JLabel fatBody;
    private javax.swing.JLabel fatbod;
    public static javax.swing.JLabel gizi2;
    private javax.swing.JLabel hearts;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel jenisKelamin2;
    public static javax.swing.JLabel karbo2;
    public static javax.swing.JLabel lemaks2;
    private javax.swing.JLabel logo;
    public static javax.swing.JLabel namaUser2;
    public static javax.swing.JLabel proto2;
    private javax.swing.JLabel resultt3;
    private javax.swing.JLabel satuan;
    public static javax.swing.JLabel tinggiBadan2;
    public static javax.swing.JLabel umurUser2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/painlessgui/Painlessicon.png")));
    }
}
