/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painlessgui2;

/**
 *
 * @author BiBul
 */
public class wherepain extends javax.swing.JFrame {

    /**
     * Creates new form wherepain
     */
    public wherepain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Depan = new javax.swing.JButton();
        kiri = new javax.swing.JButton();
        kanaan = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        subtitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Side.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 260, -1));

        Depan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Depan copy.png"))); // NOI18N
        Depan.setContentAreaFilled(false);
        Depan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepanMouseExited(evt);
            }
        });
        Depan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepanActionPerformed(evt);
            }
        });
        jPanel1.add(Depan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 100, -1));

        kiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/kiri copy.png"))); // NOI18N
        kiri.setContentAreaFilled(false);
        kiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kiriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kiriMouseExited(evt);
            }
        });
        kiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiriActionPerformed(evt);
            }
        });
        jPanel1.add(kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 100, -1));

        kanaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Kanan kepala copy.png"))); // NOI18N
        kanaan.setContentAreaFilled(false);
        kanaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kanaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kanaanMouseExited(evt);
            }
        });
        kanaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kanaanActionPerformed(evt);
            }
        });
        jPanel1.add(kanaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 100, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Kepala Belakang copy.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Where Do You FeeL Pain_.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 470, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/PainLESS.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 330, -1));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b1.setContentAreaFilled(false);
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b1MouseReleased(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 60, -1));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b2.setContentAreaFilled(false);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 60, -1));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b3.setContentAreaFilled(false);
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 60, -1));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b4.setContentAreaFilled(false);
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
        });
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 60, -1));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b5.setContentAreaFilled(false);
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 60, -1));

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b6.setContentAreaFilled(false);
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b6MouseExited(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 60, -1));

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b7.setContentAreaFilled(false);
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b7MouseExited(evt);
            }
        });
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 60, -1));

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b8.setContentAreaFilled(false);
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b8MouseExited(evt);
            }
        });
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 60, -1));

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b9.setContentAreaFilled(false);
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b9MouseExited(evt);
            }
        });
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 60, -1));

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png"))); // NOI18N
        b10.setContentAreaFilled(false);
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b10MouseExited(evt);
            }
        });
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 60, -1));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/1.png"))); // NOI18N
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseReleased(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        subtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/how would you rate your pain _.png"))); // NOI18N
        subtitle.setText("jLabel5");
        jPanel1.add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 350, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Gradient Fill 1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepanActionPerformed

    private void kiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kiriActionPerformed

    private void kanaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kanaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kanaanActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void DepanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepanMouseEntered
        // TODO add your handling code here:
         Depan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Depan.png")));
    }//GEN-LAST:event_DepanMouseEntered

    private void DepanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepanMouseExited
        // TODO add your handling code here:
         Depan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Depan copy.png")));
    }//GEN-LAST:event_DepanMouseExited

    private void kanaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kanaanMouseEntered
        // TODO add your handling code here:
        kanaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Kanan kepala.png")));
    }//GEN-LAST:event_kanaanMouseEntered

    private void kanaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kanaanMouseExited
        // TODO add your handling code here:
        kanaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Kanan kepala copy.png")));
    }//GEN-LAST:event_kanaanMouseExited

    private void kiriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiriMouseEntered
        // TODO add your handling code here:
        kiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/kiri.png")));   
    }//GEN-LAST:event_kiriMouseEntered

    private void kiriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiriMouseExited
        // TODO add your handling code here:
        kiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/kiri copy.png")));
    }//GEN-LAST:event_kiriMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Kepala Belakang.png")));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/Kepala Belakang copy.png")));
    }//GEN-LAST:event_backMouseExited

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/1.png")));
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b1MouseExited

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        // TODO add your handling code here:
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/2.png")));
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        // TODO add your handling code here:
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b2MouseExited

    private void b1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MousePressed
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/1.png")));
    }//GEN-LAST:event_b1MousePressed

    private void b1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseReleased
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b1MouseReleased

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/1.png")));
    }//GEN-LAST:event_b1MouseClicked

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        // TODO add your handling code here:
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/3.png")));
    }//GEN-LAST:event_b3MouseEntered

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
        // TODO add your handling code here:
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b3MouseExited

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        // TODO add your handling code here:
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/4.png")));
    }//GEN-LAST:event_b4MouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        // TODO add your handling code here:
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b4MouseExited

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        // TODO add your handling code here:
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/5.png")));
    }//GEN-LAST:event_b5MouseEntered

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
        // TODO add your handling code here:
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b5MouseExited

    private void b6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseEntered
        // TODO add your handling code here:
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/6.png")));
    }//GEN-LAST:event_b6MouseEntered

    private void b6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseExited
        // TODO add your handling code here:
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b6MouseExited

    private void b7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseEntered
        // TODO add your handling code here:
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/7.png")));
    }//GEN-LAST:event_b7MouseEntered

    private void b7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseExited
        // TODO add your handling code here:
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b7MouseExited

    private void b8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseEntered
        // TODO add your handling code here:
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/8.png")));
    }//GEN-LAST:event_b8MouseEntered

    private void b8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseExited
        // TODO add your handling code here:
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b8MouseExited

    private void b9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseEntered
        // TODO add your handling code here:
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/9.png")));
    }//GEN-LAST:event_b9MouseEntered

    private void b9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseExited
        // TODO add your handling code here:
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b9MouseExited

    private void b10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseEntered
        // TODO add your handling code here:
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/10.png")));
    }//GEN-LAST:event_b10MouseEntered

    private void b10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseExited
        // TODO add your handling code here:
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/lingkar biru.png")));
    }//GEN-LAST:event_b10MouseExited

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseReleased
        // TODO add your handling code here:
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/1.png")));
    }//GEN-LAST:event_jToggleButton1MouseReleased

    private void jToggleButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MousePressed
        // TODO add your handling code here:
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui2/2.png")));
    }//GEN-LAST:event_jToggleButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wherepain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wherepain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wherepain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wherepain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wherepain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Depan;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton kanaan;
    private javax.swing.JButton kiri;
    private javax.swing.JLabel subtitle;
    // End of variables declaration//GEN-END:variables
}
