/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painlessgui;


import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;
import static painlessgui.Biodata.jDateChooser1;
import painlessgui.start;


/**
 *
 * @author USER
 */
public class BiodataDua extends javax.swing.JFrame {

    /**
     * Creates new form BiodataDua
     */
    public BiodataDua() {
        initComponents();
        setTitle("PainLESS v1.0.0");
        setIcon();
            
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/painlessgui/Painlessicon.png")));
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        TanggalLahir = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JLabel();
        isianNama = new javax.swing.JTextField();
        listJenisKelamin = new javax.swing.JComboBox();
        nextButton = new javax.swing.JToggleButton();
        logo = new javax.swing.JLabel();
        backButton = new javax.swing.JToggleButton();
        kalender = new com.toedter.calendar.JDateChooser();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 500, 40));

        judul.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        judul.setText("DATA PRIBADI");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 350, 50));

        nama.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        nama.setText("Nama");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 100, 40));

        TanggalLahir.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        TanggalLahir.setText("Tanggal lahir");
        jPanel1.add(TanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 160, 40));

        jenisKelamin.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jenisKelamin.setText("Jenis Kelamin");
        jPanel1.add(jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 140, 40));

        isianNama.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        isianNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isianNamaActionPerformed(evt);
            }
        });
        isianNama.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                isianNamaPropertyChange(evt);
            }
        });
        jPanel1.add(isianNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 280, 40));

        listJenisKelamin.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        listJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));
        listJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listJenisKelaminActionPerformed(evt);
            }
        });
        jPanel1.add(listJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 280, 40));

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/cek _.png"))); // NOI18N
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 150, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/PainLESS.png"))); // NOI18N
        logo.setText("jLabel2");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 330, 80));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/bek.png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 130, 30));
        jPanel1.add(kalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 280, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/Cloud.png"))); // NOI18N
        Background.setText("jLabel1");
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isianNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isianNamaActionPerformed
 String nama;
 
    }//GEN-LAST:event_isianNamaActionPerformed

    private void isianNamaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_isianNamaPropertyChange

    }//GEN-LAST:event_isianNamaPropertyChange

    private void listJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listJenisKelaminActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        
        
        if (isianNama.getText().trim().isEmpty()){
            jLabel2.setText("FIELD STILL EMPTY");
            JOptionPane.showMessageDialog(null, "ur mom give u a good name , so use it!");
            
        }
        
         Date lahir = kalender.getDate();
        Date kini = new Date();
        int ur = kini.getYear()-lahir.getYear();
                 
       this.setVisible(false);
       wherepain c = new wherepain();
       wherepain.jLabel7.setText("Usia mu"+" "+String.valueOf(ur)+ "thn");
       wherepain.duar.setText("hai"+" "+isianNama.getText());
       wherepain.geder.setText((String ) listJenisKelamin.getSelectedItem());
       c.setVisible(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        start c = new start ();
        c.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataDua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel TanggalLahir;
    private javax.swing.JToggleButton backButton;
    public static javax.swing.JTextField isianNama;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JLabel judul;
    public static com.toedter.calendar.JDateChooser kalender;
    private javax.swing.JComboBox listJenisKelamin;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nama;
    private javax.swing.JToggleButton nextButton;
    // End of variables declaration//GEN-END:variables
}
