/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painlessgui;

import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class resultAtasTiga extends javax.swing.JFrame {

    /**
     * Creates new form resultAtasTiga
     */
    public resultAtasTiga() {
        initComponents();
        setTitle("PainLESS v1.0.0");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        hubRumahSakit1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        sebabEnam = new javax.swing.JLabel();
        sebabSatu = new javax.swing.JLabel();
        sebabDua = new javax.swing.JLabel();
        sebabTiga = new javax.swing.JLabel();
        sebabEmpat = new javax.swing.JLabel();
        sebabLima = new javax.swing.JLabel();
        sebabTujuh = new javax.swing.JLabel();
        obatSatu = new javax.swing.JLabel();
        obatDua = new javax.swing.JLabel();
        obatTiga = new javax.swing.JLabel();
        obatEmpat = new javax.swing.JLabel();
        hubRumahSakit = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/bek.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, -1, -1));

        hubRumahSakit1.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        hubRumahSakit1.setForeground(new java.awt.Color(255, 51, 51));
        hubRumahSakit1.setText("EMERGENCY !!!");
        jPanel1.add(hubRumahSakit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/PainLESS.png"))); // NOI18N
        Logo.setText("jLabel1");
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, -1));

        sebabEnam.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        sebabEnam.setForeground(new java.awt.Color(51, 51, 51));
        sebabEnam.setText("- bekerja terlalu keras");
        jPanel1.add(sebabEnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        sebabSatu.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        sebabSatu.setForeground(new java.awt.Color(51, 51, 51));
        sebabSatu.setText("yang menyebabkan kamu sakit kepala di bagian atas adalah");
        jPanel1.add(sebabSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        sebabDua.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        sebabDua.setForeground(new java.awt.Color(51, 51, 51));
        sebabDua.setText("- kurang istirahat");
        jPanel1.add(sebabDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        sebabTiga.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        sebabTiga.setForeground(new java.awt.Color(51, 51, 51));
        sebabTiga.setText("- kelelahan");
        jPanel1.add(sebabTiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        sebabEmpat.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        sebabEmpat.setForeground(new java.awt.Color(51, 51, 51));
        sebabEmpat.setText("- rasa cemas yang berlebihan");
        jPanel1.add(sebabEmpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 20));

        sebabLima.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        sebabLima.setForeground(new java.awt.Color(51, 51, 51));
        sebabLima.setText("- stres mental");
        jPanel1.add(sebabLima, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        sebabTujuh.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        sebabTujuh.setForeground(new java.awt.Color(51, 51, 51));
        sebabTujuh.setText("- dehidrasi");
        jPanel1.add(sebabTujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        obatSatu.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        obatSatu.setForeground(new java.awt.Color(51, 51, 51));
        obatSatu.setText("untuk langkah pertama, minum obat pereda nyeri seperti :");
        jPanel1.add(obatSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        obatDua.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        obatDua.setForeground(new java.awt.Color(51, 51, 51));
        obatDua.setText("- paracetamol");
        jPanel1.add(obatDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        obatTiga.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        obatTiga.setForeground(new java.awt.Color(51, 51, 51));
        obatTiga.setText("- ibuprofen");
        jPanel1.add(obatTiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        obatEmpat.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        obatEmpat.setForeground(new java.awt.Color(51, 51, 51));
        obatEmpat.setText("- aspirin");
        jPanel1.add(obatEmpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, -1));

        hubRumahSakit.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        hubRumahSakit.setText("segera hubungi rumah sakit terdekat!");
        jPanel1.add(hubRumahSakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, -1, -1));

        background.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/Cloud.png"))); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/_BACK.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/bek.png")));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        start e = new start();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultAtasTiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultAtasTiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultAtasTiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultAtasTiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultAtasTiga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JLabel hubRumahSakit;
    private javax.swing.JLabel hubRumahSakit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel obatDua;
    private javax.swing.JLabel obatEmpat;
    private javax.swing.JLabel obatSatu;
    private javax.swing.JLabel obatTiga;
    private javax.swing.JLabel sebabDua;
    private javax.swing.JLabel sebabEmpat;
    private javax.swing.JLabel sebabEnam;
    private javax.swing.JLabel sebabLima;
    private javax.swing.JLabel sebabSatu;
    private javax.swing.JLabel sebabTiga;
    private javax.swing.JLabel sebabTujuh;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/painlessgui/Painlessicon.png")));
    }
}
