/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painlessgui;

import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class resultKananDua extends javax.swing.JFrame {

    /**
     * Creates new form resultKananDua
     */
    public resultKananDua() {
        initComponents();
        setTitle("PainLESS v1.0.0");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sebabSatu = new javax.swing.JLabel();
        sebabDua1 = new javax.swing.JLabel();
        sebabDua = new javax.swing.JLabel();
        solusiSatu = new javax.swing.JLabel();
        solusiDua = new javax.swing.JLabel();
        solusiTiga = new javax.swing.JLabel();
        solusiTujuh = new javax.swing.JLabel();
        solusiEmpat = new javax.swing.JLabel();
        solusiLima = new javax.swing.JLabel();
        gewees = new javax.swing.JLabel();
        obatSatu = new javax.swing.JLabel();
        obatSatu1 = new javax.swing.JLabel();
        obatSatu3 = new javax.swing.JLabel();
        obatSatu2 = new javax.swing.JLabel();
        obatSatu4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/bek.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/PainLESS.png"))); // NOI18N
        Logo.setText("jLabel1");
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Headache Right Head MEDIUM level");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        sebabSatu.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        sebabSatu.setText("yang menyebabkan kamu sakit kepala di bagian atas adalah");
        jPanel1.add(sebabSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        sebabDua1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        sebabDua1.setText("- tekanan dalam rongga kepala yang meningkat");
        jPanel1.add(sebabDua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        sebabDua.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        sebabDua.setText("- migrain");
        jPanel1.add(sebabDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        solusiSatu.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        solusiSatu.setText("yang harus kamu lakukan");
        jPanel1.add(solusiSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 260, -1));

        solusiDua.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        solusiDua.setText("- makan teratur");
        jPanel1.add(solusiDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        solusiTiga.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        solusiTiga.setText("- perbanyak minum air putih");
        jPanel1.add(solusiTiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        solusiTujuh.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        solusiTujuh.setText("- batasi kafein dan alkohol");
        jPanel1.add(solusiTujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        solusiEmpat.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        solusiEmpat.setText("- istirahat yang cukup");
        jPanel1.add(solusiEmpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        solusiLima.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        solusiLima.setText("- olahraga teratur");
        jPanel1.add(solusiLima, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        gewees.setFont(new java.awt.Font("Courier New", 1, 50)); // NOI18N
        gewees.setText("GET WELL SOON");
        jPanel1.add(gewees, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        obatSatu.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        obatSatu.setText("disarankan untuk mengkonsumsi obat pereda nyeri seperti :");
        jPanel1.add(obatSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        obatSatu1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        obatSatu1.setText("- aspirin");
        jPanel1.add(obatSatu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 70, 20));

        obatSatu3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        obatSatu3.setText("- naproxen (aleve)");
        jPanel1.add(obatSatu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        obatSatu2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        obatSatu2.setText("- acetaminaphen(tylenol)");
        jPanel1.add(obatSatu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, -1));

        obatSatu4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        obatSatu4.setText("- ibuprofen (advil,motrin)");
        jPanel1.add(obatSatu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        background.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/Cloud.png"))); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/_BACK.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painlessgui/bek.png")));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        start e = new start();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultKananDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultKananDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultKananDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultKananDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultKananDua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JLabel gewees;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel obatSatu;
    private javax.swing.JLabel obatSatu1;
    private javax.swing.JLabel obatSatu2;
    private javax.swing.JLabel obatSatu3;
    private javax.swing.JLabel obatSatu4;
    private javax.swing.JLabel sebabDua;
    private javax.swing.JLabel sebabDua1;
    private javax.swing.JLabel sebabSatu;
    private javax.swing.JLabel solusiDua;
    private javax.swing.JLabel solusiEmpat;
    private javax.swing.JLabel solusiLima;
    private javax.swing.JLabel solusiSatu;
    private javax.swing.JLabel solusiTiga;
    private javax.swing.JLabel solusiTujuh;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/painlessgui/Painlessicon.png")));
    }
}
